apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-test
spec:
  template:
    metadata:
      labels:
        app: deployment-test
        ver: 2.0.0
    spec:
      containers:
      - name: nginx
        image: nginx:latest
      - name: redis
        image: redis:latest

