#!/bin/bash

remote="$1"
url="$2"

z40=0000000000000000000000000000000000000000

while read local_ref local_sha remote_ref remote_sha
do
    if [ "$local_sha" = $z40 ]
    then
        # Handle delete
        :
    else
        if [ "$remote_sha" = $z40 ]
        then
            # New branch, examine all commits
            range="$local_sha"
        else
            # Update to existing branch, examine new commits
            range="$remote_sha..$local_sha"
        fi

        commit=`git diff --name-only "$range"`
        if [ -n "$commit" ]
            for file in $commit; do
                case "${file##*.}" in
                    pl | pm | t)
                        echo $file
                        #perlcritic -5 --verbose 8 $file || exit 1
                        ;;
                    *)
                        ;;
                esac
            done
            exit 0
        then
            exit 1
        fi
    fi
done

exit 0
