#----------------------------------------------------------
# Theme
#----------------------------------------------------------
[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'morhetz/gruvbox'

#----------------------------------------------------------
# Git
#----------------------------------------------------------
[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
let g:gitgutter_override_sign_column_highlight = 0
highlight GitGutterAdd ctermfg=blue ctermbg=brown
'''

[[plugins]]
repo = 'tpope/vim-fugitive'

#----------------------------------------------------------
# NERD
#----------------------------------------------------------
[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'jistr/vim-nerdtree-tabs'

#----------------------------------------------------------
# fzf
#----------------------------------------------------------
[[plugins]]
repo = 'junegunn/fzf'
build_on = '''
./install -all
'''

[[plugins]]
repo = 'junegunn/fzf.vim'

#----------------------------------------------------------
# coc
#----------------------------------------------------------
[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
on_i = 1
merged = '0'
hook_source = 'call coil398#init#coc#hook_source()'
