[tools]
jq = "latest"
fzf = "latest"
eza = "latest"
ruby = "latest"
awscli = "latest"
node = "latest"
actionlint = "latest"
conftest = "latest"
golangci-lint = "latest"
go = "1.23.2"
gh = "latest"
usage = "latest"
bat = "latest"
delta = "latest"
pre-commit = "4.0.1"
terraform = "1.10.1"
terraformer = "latest"
hub = "latest"
ecspresso = "latest"
duf = "latest"
yarn = "latest"
rust = "latest"
