[tools]
jq = "latest"
fzf = "latest"
eza = "latest"
conftest = "latest"
golangci-lint = "latest"
go = "1.23.2"
gh = "latest"
usage = "latest"
bat = "latest"
delta = "latest"
pre-commit = "4.0.1"
terraform = "latest"
terraformer = "latest"
hub = "latest"
ecspresso = "latest"
duf = "latest"
yarn = "latest"
rust = "latest"
deno = "latest"
uv = "latest"
colima = "latest"
gcloud = "latest"
ghq = "latest"
cmake = "latest"
k6 = "latest"
pnpm = "latest"
shellcheck = "latest"
sqlite = "latest"
ollama = "latest"
yq = "latest"
ripgrep = "latest"
actionlint = "latest"
trivy = "latest"
python = "3.12.9"
node = "23.6.0"
ruby = "3.1.7"
aws-cli = { version = "latest", symlink_bins = "true" }

[env]
