apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: deployment-test
spec:
  template:
    metadata:
      labels:
        app: deployment-test
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        args: ["test", "-f"]
      - name: nginx2
        image: nginx:alpine2
        args: ["test", "-f"]
