- hosts: localhost
  connection: local
  vars:
    homebrew_taps:
      - homebrew/core
      - jesseduffield/lazydocker
      - sanemat/font
      - heroku/brew

    brew_cask_apps:
      - alfred
      - clipy
      - docker
      - firefox
      - google-chrome
      - google-japanese-ime
      - google-hangouts
      - iterm2
      - licecap
      - snip
      - visual-studio-code

    homebrew_packages:
      -  ansible
      -  autoconf
      -  automake
      -  bash
      -  cairo
      -  circleci
      -  ctags
      -  figlet
      -  fontconfig
      -  fontforge
      -  freetype
      -  fribidi
      -  gd
      -  gdbm
      -  gettext
      -  giflib
      -  glib
      -  go
      -  graphite2
      -  graphviz
      -  gts
      -  hadolint
      -  harfbuzz
      -  heroku
      -  heroku-node
      -  htop
      -  icu4c
      -  jasper
      -  jemalloc
      -  jpeg
      -  jq
      -  lazydocker
      -  lazygit
      -  libffi
      -  libpng
      -  libspiro
      -  libtermkey
      -  libtiff
      -  libtool
      -  libuninameslist
      -  libuv
      -  libvterm
      -  libyaml
      -  luajit
      -  lzo
      -  msgpack
      -  ncurses
      -  neovim
      -  netpbm
      -  node
      -  oniguruma
      -  openssl
      -  pango
      -  pcre
      -  pixman
      -  pkg-config
      -  plantuml
      -  python
      -  python@2
      -  readline
      -  ricty
      -  sqlite
      -  tree
      -  unibilium
      -  webp
      -  xz
      -  zsh

  tasks:
    - name: homebrew update
      homebrew:
        update_homebrew: yes

    # - name: Install Homebrew Cask Packages
      # homebrew_cask:
        # name: "{{ item }}"
        # state: "present"
        # install_options: "appdir=/Applications"
        # accept_external_apps: yes
      # with_items: "{{ brew_cask_apps }}"
       # upgrade_all: yes

    - name: homebrew tap
      homebrew_tap:
        name: '{{ item }}'
        state: present
      with_items: '{{ homebrew_taps }}'

    - name: homebrew packages install
      homebrew:
        name: '{{ item }}'
        state: present
      with_items: '{{ homebrew_packages }}'
